with source_data as (
    select *
    from {{ ref('stg_bts_on_time_performance') }}
)

SELECT

    {{ dbt_utils.generate_surrogate_key([
        'fl_date',
        'mkt_unique_carrier',
        'op_unique_carrier',
        'sch_op_carrier_fl_num',
        'origin_airport_seq_id',
        'dest_airport_seq_id',
        'crs_dep_time',
        'crs_arr_time',
        'dup',
        'is_cancelled'
    ]) }} as flight_record_key,
    fl_date,
    mkt_unique_carrier,
    SAFE_CAST(sch_op_carrier_fl_num AS INT64) AS sch_op_carrier_fl_num,
    op_unique_carrier,
    SAFE_CAST(origin_airport_id AS INT64) AS origin_airport_id,
    SAFE_CAST(origin_airport_seq_id AS INT64) AS origin_airport_seq_id,
    SAFE_CAST(origin_city_market_id AS INT64) AS origin_city_market_id,
    origin,
    origin_city_name,
    origin_state_abr,
    origin_state_fips,
    origin_state_nm,
    SAFE_CAST(origin_wac AS INT64) AS origin_wac,
    SAFE_CAST(dest_airport_id AS INT64) AS dest_airport_id,
    SAFE_CAST(dest_airport_seq_id AS INT64) AS dest_airport_seq_id,
    SAFE_CAST(dest_city_market_id AS INT64) AS dest_city_market_id,
    dest,
    dest_city_name,
    dest_state_abr,
    dest_state_fips,
    dest_state_nm,
    SAFE_CAST(dest_wac AS INT64) AS dest_wac,
    crs_dep_time,
    dep_time,
    SAFE_CAST(dep_delay AS INT64) AS dep_delay,
    SAFE_CAST(dep_delay_new AS INT64) AS dep_delay_new,
    SAFE_CAST(dep_del15 AS INT64) AS dep_del15,
    SAFE_CAST(dep_delay_group AS INT64) AS dep_delay_group,
    dep_time_blk,
    SAFE_CAST(taxi_out AS INT64) AS taxi_out,
    wheels_off,
    wheels_on,
    SAFE_CAST(taxi_in AS INT64) AS taxi_in,
    crs_arr_time,
    arr_time,
    SAFE_CAST(arr_delay AS INT64) AS arr_delay,
    SAFE_CAST(arr_delay_new AS INT64) AS arr_delay_new,
    SAFE_CAST(arr_del15 AS INT64) AS arr_del15,
    SAFE_CAST(arr_delay_group AS INT64) AS arr_delay_group,
    arr_time_blk,
    is_cancelled,
    cancellation_code,
    is_diverted,
    dup,
    SAFE_CAST(crs_elapsed_time AS INT64) AS crs_elapsed_time,
    SAFE_CAST(actual_elapsed_time AS INT64) AS actual_elapsed_time,
    SAFE_CAST(air_time AS INT64) AS air_time,
    SAFE_CAST(flights AS INT64) AS flights,
    SAFE_CAST(distance AS INT64) AS distance,
    SAFE_CAST(distance_group AS INT64) AS distance_group,
    SAFE_CAST(carrier_delay AS INT64) AS carrier_delay,
    SAFE_CAST(weather_delay AS INT64) AS weather_delay,
    SAFE_CAST(nas_delay AS INT64) AS nas_delay,
    SAFE_CAST(security_delay AS INT64) AS security_delay,
    first_dep_time,
    SAFE_CAST(total_add_gtime AS INT64) AS total_add_gtime,
    SAFE_CAST(longest_add_gtime AS INT64) AS longest_add_gtime,
    SAFE_CAST(div_airport_landings AS INT64) AS div_airport_landings
FROM source_data
